### ISSUE TITLE
怎样给自定义view添加点击事件？

### ISSUE THREAD

**Issue by lindow2009** [Gavin-ZYX/StickyDecoration#1]
实现了自定义view的悬浮，但是自定义view能加上点击事件么？

**Comment by Gavin-ZYX** [comment]
点击事件的话，博客的评论中有提到几种方案。可以作为参考，不过个人觉得不够优雅。
链接——http://www.jianshu.com/p/b335b620af39

**Comment by Gavin-ZYX** [comment]
1.2.0中已支持点击事件
