### ISSUE TITLE
当RecyclerView不宽度不是屏幕宽度时有bug，已提供修改方法

### ISSUE THREAD

**Issue by github-zhanghang** [Gavin-ZYX/StickyDecoration#12]
将StickyDecoration中onDrawOver方法中的final int left = parent.getLeft() + parent.getPaddingLeft();
改成final int left = parent.getPaddingLeft();  按照你的来做，当RecyclerView的宽度小于屏幕宽度时，悬浮栏的左边起点位置就会加上这个parent.getLeft(),导致悬浮栏的宽度小于item的宽度

**Comment by Gavin-ZYX** [comment]
已修复，谢谢！
