### ISSUE TITLE
StickyDecoration中设置文字颜色后没有重新设置Paint的颜色

### ISSUE THREAD

**Issue by smartown** [Gavin-ZYX/StickyDecoration#16]
StickyDecoration中设置文字颜色后没有重新设置Paint的颜色，设置后的颜色没得到应用，颜色始终为白色。

**Comment by Gavin-ZYX** [comment]
我检查了下，没发现你说的问题。请问你是怎么用的？

**Comment by smartown** [comment]
我看你源码已经改了，可能是我们项目用的是你以前版本的库吧。
