### ISSUE TITLE
如果是一个占满屏幕的布局作为浮动标题你的测量有问题

### ISSUE THREAD

**Issue by mm46468648** [Gavin-ZYX/StickyDecoration#18]
只会在大约左边300px的区域绘制,而且使用权重完全失效

**Comment by Gavin-ZYX** [comment]
绘制内容的宽度只能子View测量，布局中宽度的match_parent、权重是没用的。
作为补偿，目前使用isAlignLeft来处理左右的放置。

**Comment by woshiyanxiong** [comment]
为啥图片在后边 文字在左边 会出现 显示混乱呢 绘制之后

**Comment by Gavin-ZYX** [comment]
可能跟你的布局有关，你把布局发出来看看

**Comment by woshiyanxiong** [comment]
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="50dp">
        <TextView
            android:layout_alignParentLeft="true"
            android:layout_marginLeft="15dp"
            android:gravity="center|left"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:text="测速"
            android:textSize="16sp"
            />
        <ImageView
            android:layout_centerVertical="true"
            android:layout_alignParentRight="true"
            android:layout_marginRight="15dp"
            android:layout_width="33dp"
            android:layout_height="33dp"
            android:src="@drawable/avatar4"/>
    </RelativeLayout>

</LinearLayout>`
![default](https://user-images.githubusercontent.com/17847175/34930628-5bf35f9a-fa05-11e7-830f-ee493bdc31e4.png)

**Comment by woshiyanxiong** [comment]
![default](https://user-images.githubusercontent.com/17847175/34930634-6aafcc6c-fa05-11e7-9030-4a741f20b00a.png)
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="50dp">
        <TextView
            android:layout_alignParentLeft="true"
            android:layout_marginLeft="15dp"
            android:gravity="center|left"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:text="测速"
            android:textSize="16sp"
            />
        <ImageView
            android:layout_centerVertical="true"
            android:layout_alignParentRight="true"
            android:layout_marginRight="15dp"
            android:layout_width="33dp"
            android:layout_height="33dp"
            android:src="@drawable/avatar4"/>
    </RelativeLayout>

</LinearLayout>

**Comment by woshiyanxiong** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="50dp">
        <TextView
            android:layout_alignParentLeft="true"
            android:layout_marginLeft="15dp"
            android:gravity="center|left"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:text="测速"
            android:textSize="16sp"
            />
        <ImageView
            android:layout_centerVertical="true"
            android:layout_alignParentRight="true"
            android:layout_marginRight="15dp"
            android:layout_width="33dp"
            android:layout_height="33dp"
            android:src="@drawable/avatar4"/>
    </RelativeLayout>

</LinearLayout>

**Comment by Gavin-ZYX** [comment]
这种布局确实存在问题，计算的宽度不准确。这问题我找个是时间看下，能不能处理掉

**Comment by Gavin-ZYX** [comment]
fixed in v1.3.0
