### ISSUE TITLE
添加groupView的时候能不能 match_parent ,否则我自定义的view需要右对齐就不行了

### ISSUE THREAD

**Issue by shark5** [Gavin-ZYX/StickyDecoration#2]
//根据position获取View
            View groupView = getGroupView(position);
            if (groupView == null) return;
            ViewGroup.LayoutParams layoutParams = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.**_WRAP_CONTENT_**, mGroupHeight);
            groupView.setLayoutParams(layoutParams);
            groupView.setDrawingCacheEnabled(true);
            groupView.measure(
                    View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED),
                    View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED));
            //指定高度、宽度的groupView
            groupView.layout(0, 0, right, mGroupHeight);
            groupView.buildDrawingCache();
            Bitmap bitmap = groupView.getDrawingCache();
            int marginLeft = isAlignLeft ? 0 : right - groupView.getMeasuredWidth();
            c.drawBitmap(bitmap, left + marginLeft, top - mGroupHeight, null);

**Comment by Gavin-ZYX** [comment]
其实，我代码里面一直有个方法叫isAlignLeft(boolean b)。你可以调用这个方法，参数传入false时，就会靠右显示了。
不过左边的部分会是透明的。

我还在找更好的处理方案，你可以先用这个方法实现靠右显示。

**Comment by Gavin-ZYX** [comment]
使用.isAlignLeft(false)  实现靠右边的效果，如果还要设置整条的背景色，可以调用.setGroupBackground方法设置。
代码还未上传到JCenter，Github中已更新。

**Comment by Gavin-ZYX** [comment]
1.1.0中已添加

**Comment by shark5** [comment]
Thanks

**Comment by IdioticMadman** [comment]
有没有办法，这个view可以定制多样，不是靠右或者靠中，可以直接view什么样，这个头部就什么样
