### ISSUE TITLE
关于悬浮条内View的点击事件

### ISSUE THREAD

**Issue by wulicaidada** [Gavin-ZYX/StickyDecoration#20]
这个库用recycleView来写城市选择列表很好，可以加上一个自定义的SlideBar就更完美了。不过更多的应用场景是，recycleView复杂布局时，只想让某一条View悬浮，并且需要获取该View内的子View的点击事件，您看看能不能在此基础上回调出悬浮条子View的点击事件！

**Comment by Gavin-ZYX** [comment]
SideBar的话，是个补充，可以用个新的Decoration。
关于点击事件，这个还是蛮麻烦的，我试试能不能后续补充上来。

**Comment by Gavin-ZYX** [comment]
已在1.4.2中，新增子view的点击事件
