### ISSUE TITLE
使用GridLayoutManager时，如何才能再设置每一个格子的分割线？

### ISSUE THREAD

**Issue by Lsy1992** [Gavin-ZYX/StickyDecoration#21]
.setDivideColor() //分割线颜色
  .setDivideHeight()     //分割线高度

使用这两个方法并不能让没一格设置分割线

**Comment by Lsy1992** [comment]
另外，还有一个Bug, 也是在GridLayoutManager的时候，如果有某一组的数据只有一条时，会把其他组的数据一起加到这里边，导致显示了组名和数据不对应的问题

**Comment by Gavin-ZYX** [comment]
好的，感谢你的反映。我将尽快处理

**Comment by Gavin-ZYX** [comment]
我试了了下，没有发现你说的这两个问题。
可能原因：1、是使用的版本过低（你可以试试最新版本）；2、你的数据有问题。
