### ISSUE TITLE
加载网络图片 不显示！！！急急急！！！

### ISSUE THREAD

**Issue by chenenqiang12345** [Gavin-ZYX/StickyDecoration#23]
加载网络图片 不显示！！！急急急！！！

**Comment by Gavin-ZYX** [comment]
由于图片的加载是异步的，在还没有得到图片的时候，就已经把View转化成Bitmap用来显示了，所以网络图片应该是加载不出来的。
这是个问题

**Comment by chenenqiang12345** [comment]
咋处理 急 ！！还有性能问题 ，getGroupName方法过于平凡调用

**Comment by chenenqiang12345** [comment]
咋处理 急 ！！还有性能问题 ，getGroupName方法过于平凡调用，view也是平凡创建求速度处理

**Comment by chenenqiang12345** [comment]
咋办 ，网络图片不可避免，急需这功能！！！！！！！！！11

**Comment by Gavin-ZYX** [comment]
这就很尴尬了，我周末看看能不能修复了

**Comment by Gavin-ZYX** [comment]
1.4.0中已添加异步操作后的刷新，可以解决网络图片问题
