### ISSUE TITLE
上拉或下拉刷新有问题

### ISSUE THREAD

**Issue by scmyxj** [Gavin-ZYX/StickyDecoration#24]
如果RecyclerView上面有SmartRefreshLayout用于刷新，则会导致，我下拉刷新后，那个悬浮栏就往下移动一定的距离，同时悬浮栏和顶部有一定距离的白底，再次下拉刷新后，悬浮栏在之前的基础上继续往下移动，白底继续增大，可有解决思路呢？

**Comment by Clearlee** [comment]
我也遇到这个问题了，兄弟你解决了没？

**Comment by Gavin-ZYX** [comment]
你们是每次刷新列表的时候，调用了RecyclerView.addItemDecoration(decoration)吧？
addItemDecoration方法只要调一次就可以了
