### ISSUE TITLE
怎样获取当前悬浮停留的view呢？或者怎样知道当前悬浮停留的item呢？

### ISSUE THREAD

**Issue by Achenglove** [Gavin-ZYX/StickyDecoration#25]

**Comment by Gavin-ZYX** [comment]
你指的是当前悬浮在顶部的内容吗？若果是——
1、这些这些内容都是通过Canvas画出来的，如果没有缓存的话，从我这是拿不到这个View的；
2、顶部的内容其实就是当前RecyclerView第一个可见Item的position，有了position的值也就能得到对应的View了。

**Comment by Gavin-ZYX** [comment]
你指的是当前悬浮在顶部的内容吗？若果是——
1、这些这些内容都是通过Canvas画出来的，如果没有缓存的话，从我这是拿不到这个View的；
2、顶部的内容其实就是当前RecyclerView第一个可见Item的position，有了position的值也就能得到对应的View了。

**Comment by Achenglove** [comment]
你有没有看过支付宝账单那个列表？当滚动列表到达悬浮位置时才会显示悬浮item的右边图标，这个功能的实现需要知道当前悬浮item是哪一个吧？

**Comment by Gavin-ZYX** [comment]
这样的情况有点特殊啊，处理起来有点麻烦。

**解决方案如下：**

> 这种情况可能就要监听RecyclerView的滚动了，
> 首先，监听滚动，得到位于顶部的Item的position1；
> 然后，通过这个position1 找到position1 所在的Group的第一个position2；（如：在{a、a、b、b、b、b}中，若position1为0\1，position2为0。若position1为2\3\4\5，position2为2）；
> 接着，通过position2得到viewGroup（这个viewGroup是带有右边小图标的）；
> 最后，调用notifyRedraw(recyclerView, viewGroup, position2)通知刷新就好了。

**还有，不要使用缓存**
**注意**：这样频繁的刷新可能会卡顿

我看了下ios版的支付宝，就在RecyclerView的右上角固定了一个小图标，不会因为滚动而变化，那样更简单些

**Comment by Achenglove** [comment]
苹果那种做法确实的一个比较简单的一个做法，但是android的话按照当前你的这个demo处理起来确实有点麻烦，不过非常感谢你的分享以及回答
