### ISSUE TITLE
急急急急！刷新后数据变动，但是 decoration 依然是第一次的视图数据，无法对应刷新后的数据！！！

### ISSUE THREAD

**Issue by chenenqiang12345** [Gavin-ZYX/StickyDecoration#26]
急急急急！刷新后数据变动，但是 decoration 依然是第一次的视图数据，无法对应刷新后的数据！！！老板 急需这功能！

**Comment by chenenqiang12345** [comment]
改变数据后，数据错乱

**Comment by Achenglove** [comment]
不会啊，我用了都不会出现这种情况

**Comment by Gavin-ZYX** [comment]
你用的是PowerfulStickyDecoration吧？
这是缓存引起的问题，在1.4.1中已经修复。
在1.4.1中默认关闭缓存，如果需要开启缓存的话，可以通过.setCacheEnable(true)开启，且在数据发生变化时通过decoration. cleanCache()来清除缓存也是可以的。
感谢你的issue。

**Comment by chenenqiang12345** [comment]
@Gavin-ZYX 明显卡顿了 速度处理

**Comment by chenenqiang12345** [comment]
@Gavin-ZYX 而且网络图片加载不出来了
