### ISSUE TITLE
性能略差

### ISSUE THREAD

**Issue by CaiJingLong** [Gavin-ZYX/StickyDecoration#29]
我这里用的公司的测试机
在未使用这个decoration前一切安好,使用后出现明显掉帧的情况

**Comment by Gavin-ZYX** [comment]
请问你用的是什么机型。
我目前用的手机比较好，没有太大的感觉。不过做优化还是很有必要的，我找个差点的手机试试。

**Comment by CaiJingLong** [comment]
用的配置较低 GEM-307LT

大概配置是 Hisilicon Kirin 930 CPU 
2G运存

分辨率是1200*1920

EMUI 4.0 /Android 6.0
