### ISSUE TITLE
很奇怪，作者你写好的控件，就好好维护下么，看看需求。

### ISSUE THREAD

**Issue by maoai-xianyu** [Gavin-ZYX/StickyDecoration#3]
当我用RecyclePagerAdapter 加载多个页面的布局。滑动好多页，每个页面展示每个班的班级名称和班级的，然后在各个班级中分不同的成绩档（90以上）（80~90）.. 这个是我的这组。页面的加载会刷新数据，PowerfulStickyDecoration  的分组，组会被复用多出一条。比如在（90以上）上面多一条透明的和（90以上）分组一样高度的拦。单个页面不会有这个问题，我查是复用的问题。

**Comment by Gavin-ZYX** [comment]
请不要带有情绪，谢谢。
有空的时候，我会将问题一一修复。

如果你急，可以上源码看看，毕竟没多少代码。如果能自己解决，这样是不是会有更大的收货？

**Comment by maoai-xianyu** [comment]
没有情绪的，我用别的方案修复了。因为看到下面有人提问题，你没有回复。我就写下鲜明的标题，引起关注。嘿嘿，看来可行。谢谢你得回复。

**Comment by Gavin-ZYX** [comment]
不好意思，最近有点忙。我会找个时间一一修复的

**Comment by Gavin-ZYX** [comment]
机智的小伙子，你成功把我引出来了

**Comment by maoai-xianyu** [comment]
啊哈，你有时间。改的时候记得通知。

**Comment by NelsonJs** [comment]
解决了吗解决了吗，我也碰到这个问题~~

**Comment by maoai-xianyu** [comment]
目前还没有，作者比较忙。等作者有时间吧

**Comment by NelsonJs** [comment]
看到你说有其他方案解决，可以弱弱的问下，你的解决方案吗。。

**Comment by maoai-xianyu** [comment]
你的需求是分组之后要顶部悬停么？1、如果不需要，可以用receyelerview的多布局复用，不知道你得数据格式，但是如果你现在的数据不能满足多布局复用，那就拿下数据对数据进行重组。2、或者就是一组数据，在你解析的实体类中，添加字段已满足你得需求。分组悬停的，我还没有很好方案，如你页面，可以使用下listview。

**Comment by NelsonJs** [comment]
好吧，我这仅仅只是一类数据，不存在多布局。只能再研究研究了

**Comment by ModirGithub** [comment]
خوب یه طوری بنویسین همه استفاده کنن داداش
