### ISSUE TITLE
滑动中不能监听最新展示悬浮头

### ISSUE THREAD

**Issue by Diosamo** [Gavin-ZYX/StickyDecoration#30]
当最不同组的悬浮头View滑动到顶部,顶出悬浮头以后,没有监听

**Comment by Gavin-ZYX** [comment]
这个后续可以加上监听

**Comment by Gavin-ZYX** [comment]
考虑了下
这样的功能，直接在RecyclerView中设置监听就实现了。
当前RecyclerView中第一个Item的position不就是悬浮的那个吗？
