### ISSUE TITLE
GridLayoutManager 的时候高度会错乱楼主

### ISSUE THREAD

**Issue by yuxingfafu** [Gavin-ZYX/StickyDecoration#38]
GridLayoutManager 的时候高度会错乱楼主
![image](https://user-images.githubusercontent.com/7764483/40915170-a18f5b58-682d-11e8-8c55-c7686d54ec5d.png)

**Comment by Gavin-ZYX** [comment]
方便的话，把数据也贴出来吧，能快速定位错误

**Comment by Gavin-ZYX** [comment]
目前为止，我就发现在GridLayoutManager中用了setHeaderCount方法会导致这个问题。
这个问题我在1.4.5中修复了。不过还是不建议在GridLayoutManager中使用setHeaderCount方法。
