### ISSUE TITLE
setGroupTextColor设置字体颜色无效，代码有bug

### ISSUE THREAD

**Issue by 441907002** [Gavin-ZYX/StickyDecoration#39]
更改方案：
public StickyDecoration.Builder setGroupTextColor(@ColorInt int color) {
            mStickyDecoration.mGroupTextColor = color;
            mStickyDecoration.mTextPaint.setColor(color); //添加代码部分
            return this;
}

**Comment by Gavin-ZYX** [comment]
感谢你的反馈。
不过，这个问题在1.1.1的时候就就已经修复了。
现在的代码是这样的
```java
        public Builder setGroupTextColor(@ColorInt int color) {
            mDecoration.mGroupTextColor = color;
            mDecoration.mTextPaint.setColor(mDecoration.mGroupTextColor);
            return this;
        }
```
