### ISSUE TITLE
当Decoration的高度大于item高度时有bug

### ISSUE THREAD

**Issue by 252162875** [Gavin-ZYX/StickyDecoration#4]
当Decoration的高度大于Item高度时，在上滑时两个groupView会有重叠部分，重叠部分的高度等于Decoration和Item的高度差，具体代码如下：
 if (position + 1 < itemCount) {
                    //获取下个GroupName
                    String nextGroupName = getGroupName(position + 1);
                    //下一组的第一个View接近头部
                    if (!currentGroupName.equals(nextGroupName) && viewBottom < top) {
                        top = viewBottom;
                    }
                }

**Comment by Gavin-ZYX** [comment]
是的，确实存在这个问题

**Comment by Vander-liu** [comment]
我试着去修复了下,但是感觉还是修复不好,博主,修复好这个Bug,通知下.

**Comment by SirLYC** [comment]
groupListener添加一个查找某个组最后一个位置的方法就可以解决这个问题

//当前组最后一个item相对于屏幕第一个可见位置之差
            int lastIndexInGroupNow = mGroupListener.lastIndexInGroup(now) - firstVisible;
            if(lastIndexInGroupNow < childCount) {
                View lastView = parent.getChildAt(lastIndexInGroupNow);
                int viewBottom = lastView.getBottom();
                if (viewBottom + mHeight < bottom) {
                    bottom = viewBottom;
                }
            }

**Comment by Vander-liu** [comment]
@SirLYC  您好我想看一下你底下绘制的代码。按照你的方法应该是没问题。。但是绘制这块我有点卡主了。

**Comment by Vander-liu** [comment]
@SirLYC  如果可以的话 方便留个邮箱 么。

**Comment by Vander-liu** [comment]
@SirLYC  按照你的方案，我解决了。谢谢

                int lastIndexInGroupNow = groupListener.getLastIndexInGroup(position) - firstVisible;
                if (lastIndexInGroupNow < childCount) {
                    View lastView = parent.getChildAt(lastIndexInGroupNow);
                    int mLastViewBottom = lastView.getBottom();
                    Log.d("数据测试", "最下层的View底部   :" + mLastViewBottom);
                    Log.d("数据测试", "数据比较" +"  A :"  +(mLastViewBottom + height)  +"  B   :" + top);
                    if (mLastViewBottom  < top) {
                        top = mLastViewBottom;
                    }
                }

因为后面的代码不太清除，我的变量用的可能和你的不一致，总体来说 你的思路给我很大帮助 谢谢。

**Comment by 252162875** [comment]
@Vander-liu 待会我也试试

**Comment by Vander-liu** [comment]
我把我的方法 贴出来。

    @Override
    public void onDrawOver(Canvas c, RecyclerView parent, RecyclerView.State state) {
        super.onDrawOver(c, parent, state);
        final int itemCount = state.getItemCount();
        final int childCount = parent.getChildCount();
        final int left = parent.getLeft() + parent.getPaddingLeft();
        final int right = parent.getRight() - parent.getPaddingRight();
        //标记上一个item对应的Group
        String preGroupName;
        //当前item对应的Group
        String currentGroupName = null;


        for (int i = 0; i < childCount; i++) {
            View view = parent.getChildAt(i);
            int height = view.getHeight();
            int position = parent.getChildAdapterPosition(view);

            preGroupName = currentGroupName;
            currentGroupName = groupListener.getGroupName(position);

            if (TextUtils.isEmpty(currentGroupName) || TextUtils.equals(currentGroupName, preGroupName)) {
                continue;
            }

            int viewBottom = view.getBottom();
            float top = Math.max(mGroupHeight, view.getTop());
            firstVisible = mLinearLayoutManager.findFirstVisibleItemPosition();
            if (position + 1 < itemCount) {
                //获取下个GroupName
                String nextGroupName = groupListener.getGroupName(position + 1);


//                if (viewBottom < top && !TextUtils.equals(currentGroupName, nextGroupName)) {
//                    //当前项要滚出屏幕,那么分割线也跟随要滚出屏幕
//                    top = viewBottom;
//                    Log.d("测试", "viewBottom : " + top);
//                }

                int lastIndexInGroupNow = groupListener.getLastIndexInGroup(position) - firstVisible;
                if (lastIndexInGroupNow < childCount) {
                    View lastView = parent.getChildAt(lastIndexInGroupNow);
                    int mLastViewBottom = lastView.getBottom();
                    Log.d("数据测试", "最下层的View底部   :" + mLastViewBottom);
                    Log.d("数据测试", "数据比较" +"  A :"  +(mLastViewBottom + height)  +"  B   :" + top);
                    if (mLastViewBottom  < top) {
                        top = mLastViewBottom;
                    }
                }
                c.drawRect(left, top - mGroupHeight, right, top, mGroupPaint);
                //c.drawRect(left, top - mGroupHeight, right, top, mGroupPaint);
                Paint.FontMetrics fm = mTextPaint.getFontMetrics();
                float baseLine = top - (mGroupHeight - (fm.bottom - fm.top)) / 2 - fm.bottom;
                c.drawText(currentGroupName, left + 50, baseLine, mTextPaint);
            }
        }


    }

**Comment by Vander-liu** [comment]
后续给大家参考下，解决是解决了，但是我认为这个项目更多的是给 大家提供一个思路，如果在项目中实际使用我不太推荐，因为从扩展性，包括好多地方 这个方法都不太可取。比如加一个点击事件，这块处理我就感觉比较麻烦，而且这套方案目前来说 只能用等大的ItemHeight。

这里给大家推荐一个新方案，现在主流的RecyclerView粘性头都是这样做的。



http://www.jianshu.com/p/fe69a53502ab

**Comment by 252162875** [comment]
@Vander-liu 
 int lastIndexInGroupNow = groupListener.getLastIndexInGroup(position) - firstVisible;
            if (lastIndexInGroupNow < childCount) {
                View lastView = parent.getChildAt(lastIndexInGroupNow);
                int mLastViewBottom = lastView.getBottom();
                Log.d("数据测试", "最下层的View底部   :" + mLastViewBottom);
                Log.d("数据测试", "数据比较" +"  A :"  +(mLastViewBottom + height)  +"  B   :" + top);
                if (mLastViewBottom  < top) {
                    top = mLastViewBottom;
                }
            }
把GroupListener.getLastIndexInGroup的具体实现贴出来看看啊~~~

**Comment by Vander-liu** [comment]
@252162875  你看上面啊 我把 这个类的代码 都贴出来了啊,昨天就回复完了.

**Comment by 252162875** [comment]
@Vander-liu 哪个方法的具体实现不是应该在Activity里面吗~~~没在这个里面啊

**Comment by Vander-liu** [comment]
@252162875  那个实现的方法 是自己来写的 传进去一个position,然后确定当前组的最后一个位置在哪,返回回来,这个每个人的实现方式不同啊.

我是
if(pos <= 5>){
  return 5;
}else if (pos >5 && pos <=15){
  return 15;
}

这个自己按自己的方法写的又不统一.

**Comment by Vander-liu** [comment]
@252162875 那就是一个接口,自己来实现 ,按照 这个方式来 返回值就可以.

    @Override
    public String getGroupName(int position) {
        if (position <= 5) {
            return "辽宁";
        } else if (position > 5 && position <= 15) {
            return "浙江";
        } else if (position > 15 && position <= 20) {
            return "重庆";
        } else {
            return "吉林";
        }
    }

    @Override
    public int getLastIndexInGroup(int group) {
        if (group <= 5) {
            return 5;
        } else if (group > 5 && group <= 15) {
            return 15;
        } else if (group > 15 && group <= 20) {
            return 20;
        } else {
            return 100;
        }
    }

**Comment by 252162875** [comment]
哦哦，知道了
