### ISSUE TITLE
分页加载抬头就会闪烁一下

### ISSUE THREAD

**Issue by FanChael** [Gavin-ZYX/StickyDecoration#40]
大神哥，这个我再做分页加载，然后刷新，抬头就会闪烁一下(看上去就像是分页加载刷新后被顶没了，然后又绘制了)：

这是我分页加载的刷新:
mList.addAll(infoFlash);
adapter.notifyDataSetChanged();

**Comment by FanChael** [comment]
不好意思，我发现是由于上拉加载向上平移动画导致的顶上去了。目前只能修改上拉加载更多转圈动画（不让内容进行移动）.不知道大会大神有什么更好的方案。

**Comment by Gavin-ZYX** [comment]
试了一下，发现不可行。

**SmartRefreshLayout上拉加载更多分为两个过程**
> 1、Ta通过指向上滑动的这个过程，改变translationY，实现上拉加载。
2、加载更多结束后，继续通过改变translationY实现加载结束的操作

对于1这个过程，没什么问题。可以时时得到他的translationY，计算后正确的绘制内容。

不过对于2这个过程，就显得棘手了。在加载更多结束后，布局的隐藏过程我无法监听到，因此我也无法通过translationY去改变位置。就会出现这样的情况（布局回弹时绘制出错）：
![](https://upload-images.jianshu.io/upload_images/1638147-921402b5bab8125a.gif?imageMogr2/auto-orient/strip)
（不过这个问题也不是不能解决，可以在回弹的时候不断通知recyclerView刷新【这种做法也太那个啥了~~】）

就是这两种情况都解决了，也还是不可行。因为这些动画还有回弹啊，各种神奇的的操作，这些过程大多没有监听，So~~从入门到放弃

遇到这样改变偏移的情况，怂一把，认输好了~~

（目前没想到有好的解决方案）

**Comment by Gavin-ZYX** [comment]
![](https://upload-images.jianshu.io/upload_images/1638147-c85cd7d39800cf28.gif?imageMogr2/auto-orient/strip)

**Comment by FanChael** [comment]
可以，老哥。稳 黄磊 邮箱：huangleililei@gmail.com 签名由 网易邮箱大师 定制 在2018年08月01日 21:35，zhouyouxi 写道： — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
