### ISSUE TITLE
powerstickydecoration数据加载多了后，卡顿明显

### ISSUE THREAD

**Issue by csrbzhb** [Gavin-ZYX/StickyDecoration#41]
猜测卡顿原因是在查找first位置这个函数。
关于view的缓存，可以直接用hashmap,进行缓存并且直接get，当数据量大是，可以清除过期hashmap上的view。

**Comment by Gavin-ZYX** [comment]
请问你开启缓存了吗？没有开缓存的话，一直不断的创建，开销很大。
开启后会好很多

**Comment by MarsToken** [comment]
设计不合理，原因找到了，如果一个组下有1万条数据，那么如果把对应分组关掉，虽然肉眼看不到1万条item，但是onViewCreated还是会走的，条目越多越卡！测试发现用不到10000条，3位数就可以导致anr
