### ISSUE TITLE
setStrongReference方法怎么没了，没这个方法数据会有问题

### ISSUE THREAD

**Issue by chenenqiang12345** [Gavin-ZYX/StickyDecoration#47]
setStrongReference方法怎么没了，没这个方法数据会有问题

**Comment by Gavin-ZYX** [comment]
不好意思，在新的版本中，对缓存做了一些修改。那个方法被我删了。
请问您那边的问题是什么，我尽快修复一下

**Comment by chenenqiang12345** [comment]
刷新数据recyclerView 还是第一次显示的结果，用了ClearCache没用

**Comment by Gavin-ZYX** [comment]
这个问题在1.4.7中修复了
