### ISSUE TITLE
列表中分组滑动问题，如果后面没有分组那么上一个分组头不会被顶上去

### ISSUE THREAD

**Issue by wwluo14** [Gavin-ZYX/StickyDecoration#50]

**Comment by wwluo14** [comment]
比如在demo中城市的列表中，我在列表最后的10不进行分组，那么最后的分组头在分组内容完全滚出屏幕后，不会滑出，而是会一直在屏幕顶方。 在1.3.1版本中，如果在getGroupView 和getGroupName 两个回调方法中 return null， 是没有问题的。但是在1.3.1之后，就不行了。
请问有什么解决方式没有。谢谢

**Comment by wwluo14** [comment]
我想要上下不分组，中间分组，如果用现在的版本，效果看起来就像是，上面没有分组，而中间和下面成了一个分组

**Comment by Gavin-ZYX** [comment]
你是想只有中间的那一段有悬浮效果，后面一段不要？

**Comment by wwluo14** [comment]
是的，比如浙江省下面10个城市，后面是江苏省的城市，但是江苏省的城市我不想要悬浮头，那怎么让江苏省的第一个城市，把“浙江省”这个悬浮头挤出屏幕呢？

**Comment by wwluo14** [comment]
1.3.1 这个版本是可以的，但是这个版本列表数据源更新之后，悬浮头不能及时更新，有bug

**Comment by wwluo14** [comment]
新版本可以更新数据源，但是又会出现我上面的那个问题。有什么办法解决吗？

**Comment by Gavin-ZYX** [comment]
这应该是之前那个版本的bug，我在做这个的是，就是想让null的合并到上一组。
我看下能不能通过小改动，处理你这种情况啊

**Comment by Gavin-ZYX** [comment]
我想做的效果不是这样的，所以我就不发布新版本了。

你去下源码，按下面的方法做一些改动
![image](https://user-images.githubusercontent.com/13955675/45751692-add54280-bc45-11e8-9b3e-8f1fc2f48eab.png)
PowerfulStickyDecoration的drawDecoration方法中：
注掉
```java
//c.drawRect(left, bottom - mGroupHeight, right, bottom, mGroutPaint);
```
修改
```java
int firstPositionInGroup = getFirstInGroupWithCash(position);
```
成
```java
int firstPositionInGroup = position;
```
这样就可以达到你想要的效果了（其实，这是个bug~~）

**Comment by Gavin-ZYX** [comment]
还有疑问，欢迎交流

**Comment by wwluo14** [comment]
好的明白了，感谢~
