### ISSUE TITLE
請問Group可以做到collapse/ expand嗎 ?

### ISSUE THREAD

**Issue by CMingTseng** [Gavin-ZYX/StickyDecoration#52]
Group如何 collapse child內容 ?

類似這個 
https://therubberduckdev.files.wordpress.com/2017/10/android-expandable-recyclerview.gif

**Comment by Gavin-ZYX** [comment]
**Decoration不适合做这个功能。**

想用Decoration实现这个效果，可能（我没试过）可以做到。在展开收起的时候改变数据，然后改变不同情况下的item，达到类似的效果。最后可能效果一般，还费劲。这种吃力不讨好的事情，不建议。

**个人建议**：用传统的张开收起列表，然后放个隐藏的布局来实现这个悬浮效果。

**Comment by CMingTseng** [comment]
如果要做的話

可以提示一下 在哪邊改變數據?

又有聽說是可以改變 child 的高度成為0

可以提示大約在哪個method /void嗎 ?

謝謝

**Comment by Gavin-ZYX** [comment]
我做了个例子，在app中的ExpandableActivity可以看到。

**实现思路**
1、Adapter中判断该项目是否展开，来改变高度（未展开为0）；
2、为PowerfulStickyDecoration添加setOnClickListener监听，点击后改变对应的分组数据，然后刷新悬浮窗，刷新RecyclerView。

具体用法看[ExpandableActivity](https://github.com/Gavin-ZYX/StickyDecoration/blob/master/app/src/main/java/com/gavin/com/stickydecoration/view/ExpandableActivity.java)

**效果**
功能可以实现，就是效果一般
![expandable](https://user-images.githubusercontent.com/13955675/46901063-2b0b7480-cedf-11e8-905d-980d0bcb859f.gif)
当然，代码还有优化的空间
