### ISSUE TITLE
滑动一段距离后，顶部悬浮栏点击无效

### ISSUE THREAD

**Issue by 869238519** [Gavin-ZYX/StickyDecoration#54]
滑动一段距离后（当悬浮栏下面有item的时候），顶部悬浮栏点击无效，产生的点击效果是item的而不是悬浮栏的，使用的是PowerfulStickyDecoration

**Comment by Gavin-ZYX** [comment]
参考[issue](https://github.com/Gavin-ZYX/StickyDecoration/issues/37)
