### ISSUE TITLE
最后一个展开，收缩，有问题。。

### ISSUE THREAD

**Issue by 598588152** [Gavin-ZYX/StickyDecoration#56]
最后一个展开，收缩，有问题

**Comment by 598588152** [comment]
ExpandableActivity 中当数据往上拉一部分，点击第一个收缩的item  数据没有完全隐藏

**Comment by 598588152** [comment]
可以修改么？

**Comment by Gavin-ZYX** [comment]
这是Demo上写的有点问题，只往后修改数据了。
你只要改变数据的展开类型的时候，前后修改一下就可以了。

**Comment by 598588152** [comment]
恩，谢谢。明白了。。

**Comment by 598588152** [comment]
private void changeExpandedState(int position) {
        changePlusExpandedState(position);
        changeSubtractExpandedState(--position);
    }

 private void changePlusExpandedState(int position) {
        if (list.size() > position) {
            PVWChildBean bean = list.get(position);
            bean.setExpanded(!bean.isExpanded());
            position++;
            if (list.size() > position) {
                //下个是当前分组
                PVWChildBean bean2 = list.get(position);
                if (TextUtils.equals(bean.getTitle(), bean2.getTitle())) {
                    changePlusExpandedState(position);
                }
            }
        }
    }

    private void changeSubtractExpandedState(int position) {
        if (list.size() > position && position >= 0) {
            PVWGroupBean.PVWChildBean bean = list.get(position);
            bean.setExpanded(!bean.isExpanded());
            position--;
            if (list.size() > position && position >= 0) {
                //下个是当前分组
                PVWGroupBean.PVWChildBean bean2 = list.get(position);
                if (TextUtils.equals(bean.getTitle(), bean2.getTitle())) {
                   // LogUtils.e("changeExpandedState", "Sub xxxxx  position = " + position );
                    changeSubtractExpandedState(position);
                }
            }
        }
    }

改成这样就行 ，希望有问题的人有帮助

**Comment by 598588152** [comment]
private void changeExpandedState(int position) {
        if (list.size() > position) {
          PVWChildBean bean = list.get(position);
            for (PVWChildBean childBean : list) {
                if (TextUtils.equals(bean.getTitle(), childBean.getTitle())) {
                    childBean.setExpanded(!childBean.isExpanded());
                }
            }
        }
    }

改成这样 就行 不过这遍历了整个List
