### ISSUE TITLE
使用StickyDecoration添加悬浮标题，删除item，悬浮标题可能不刷新的问题

### ISSUE THREAD

**Issue by Glenn1Wang** [Gavin-ZYX/StickyDecoration#65]
我这边的解决方法是在onDrawOver中判断childCount数量是否和上一次相同，如果不相同,则清除BaseDecoration中firstInGroupCash的缓存

**Comment by Gavin-ZYX** [comment]
这个应该只适用于删除item的情况，如果是整个list都发生变化，你这个方法就不适用了。
简单来做，还是你知道数据发生变化了，就手动清一下缓存。取消缓存更方便，清都不用清23333
