### ISSUE TITLE
分组上面出现空白

### ISSUE THREAD

**Issue by wanglinqiang0** [Gavin-ZYX/StickyDecoration#66]
在fragment使用时  如果每次都重新初始化fragment  随着复用次数变多 ，分组上面会多出一块空白区域越来越大

**Comment by wanglinqiang0** [comment]
我看你关闭的第二页 也有人提出这个问题 但是并没有回答····

**Comment by Gavin-ZYX** [comment]
你是不是调用了多次的addDecortion?

**Comment by wanglinqiang0** [comment]
是啊 因为每次复用 都会重新初始化嘛 意思只调用一次咯？

**Comment by Gavin-ZYX** [comment]
是的呀

**Comment by Andy957** [comment]
请问这个问题如何解决？因为需要更新数据，我找不到解决的办法、

**Comment by Gavin-ZYX** [comment]
在初始化的时候调用addDecoration，后面不要调就好了
