### ISSUE TITLE
使用GridLayoutManager出现的数据混乱和高度变形

### ISSUE THREAD

**Issue by wanglinqiang0** [Gavin-ZYX/StickyDecoration#67]
如果使用GridLayoutManager的时候 设置new GridLayoutManager(getActivity(), 3); 但是数据源 每个分类没有超过3个 会出现变形
![image](https://user-images.githubusercontent.com/18564487/57899963-a0825d80-7891-11e9-98db-a3cbaafd4da1.png)
![image](https://user-images.githubusercontent.com/18564487/57900053-f6570580-7891-11e9-871a-02e22c18737d.png)
我如果把每个分类的数据源超过3个以上就是正常显示的 并不会错乱

**Comment by Gavin-ZYX** [comment]
好的，我排查一下

**Comment by Gavin-ZYX** [comment]
试了下，demo中是没有问题的。
你是不是用了setHeaderCount()方法，这方法在GridLayoutManager中是不支持的。

**Comment by wanglinqiang0** [comment]
![image](https://user-images.githubusercontent.com/18564487/57963743-af354700-795b-11e9-9d3f-c3041900f792.png)
没有啊

**Comment by Gavin-ZYX** [comment]
你代码中用的是LinearLayoutManager，图片却是GridLayoutManager，这~~

**Comment by Gavin-ZYX** [comment]
还有，GridLayoutManager是要调用resetSpan的。你参考下demo中的用法
![image](https://user-images.githubusercontent.com/13955675/57977336-e7568b80-7a28-11e9-8b96-e61dfc06f0d2.png)

**Comment by wanglinqiang0** [comment]
![image](https://user-images.githubusercontent.com/18564487/57977366-a743d880-7a29-11e9-9279-5f827c9a77ba.png)
不好意思 之前接错图了···我看了一下你的demo 好像唯一的区别就是我的adapter 用的是BaseRecyclerViewAdapterHelper框架 不是用的recycle原生的 帮我瞅瞅撒 大佬

**Comment by Gavin-ZYX** [comment]
这就要看你BaseRecyclerViewAdapterHelper的代码了，我怀疑里面有隐藏的头部。

**Comment by wanglinqiang0** [comment]
那我周一去试一下原生的用法 再看看这个问题  你demo没有问题的话 应该是我使用的问题造成的

**Comment by Gavin-ZYX** [comment]
好的。

**Comment by wanglinqiang0** [comment]
果然我使用原生的 没有出现混乱了 感谢大佬···

**Comment by liangzhanncu** [comment]
GridLayoutManager，我这边用的原生adapter，第一次设置数据正常，后面列表发生改变list.remove()后调用notifyDataSetChanged()就会发生上面的混乱情况.

**Comment by liangzhanncu** [comment]
![image](https://user-images.githubusercontent.com/24293211/58382118-ba8e0f80-7ff8-11e9-9da4-5b7788a91cba.png)

**Comment by liangzhanncu** [comment]
![image](https://user-images.githubusercontent.com/24293211/58382125-ce397600-7ff8-11e9-862f-17f55893a32e.png)

**Comment by liangzhanncu** [comment]
![image](https://user-images.githubusercontent.com/24293211/58382133-f2955280-7ff8-11e9-98d5-5c26bcccbe2d.png)

**Comment by liangzhanncu** [comment]
没有大佬解疑惑吗？是span发生了变化导致？但是横向布局span已经重新设置了的

**Comment by Gavin-ZYX** [comment]
目前还不知道是什么原因，我周末找个时间处理下。

**Comment by Gavin-ZYX** [comment]
不好意思啊，处理得有点晚。
问题在1.5.0中已解决。
