### ISSUE TITLE
如何不让某一个item不显示悬停头部

### ISSUE THREAD

**Issue by wlingf** [Gavin-ZYX/StickyDecoration#68]
GroupListener groupListener = new GroupListener() {
        @Override
        public String getGroupName(int position) {
            if (multipleList.size() > position && position != 0) {
                //获取组名，用于判断是否是同一组
                return multipleList.get(position).getTagType();
            }
            return "";
        }
    };
这样写第一个还是会显示  return null时也是一样

**Comment by Gavin-ZYX** [comment]
没有这个功能
