### ISSUE TITLE
刷新数据后，头部内容显示有误，且界面错乱

### ISSUE THREAD

**Issue by Racer23** [Gavin-ZYX/StickyDecoration#70]
首次加载 头部数据及item布局正常
![Screenshot_2019-05-29-10-52-09-210_com sevenmmobi](https://user-images.githubusercontent.com/11640864/58525947-1bd3ff80-8200-11e9-98f2-786130d476f4.png)
![_O`8P2KW4PTTIW4@NX_@M(W](https://user-images.githubusercontent.com/11640864/58525948-1c6c9600-8200-11e9-82f3-acb9e582c866.png)

刷新数据 头部数据及item布局异常
![Screenshot_2019-05-29-10-53-16-898_com sevenmmobi](https://user-images.githubusercontent.com/11640864/58525987-34441a00-8200-11e9-8a8e-57fc0cdef978.png)
![AUKMNPLR%KP0}0W_`F7SJQC](https://user-images.githubusercontent.com/11640864/58525994-38703780-8200-11e9-9e83-c7d6232d6d15.png)

**Comment by Racer23** [comment]
![1559098554(1)](https://user-images.githubusercontent.com/11640864/58526076-6c4b5d00-8200-11e9-9bae-eabfcdb83da7.jpg)
![1559098562](https://user-images.githubusercontent.com/11640864/58526078-6fdee400-8200-11e9-941b-0c5f2cddf7f2.jpg)

**Comment by Racer23** [comment]
![EQ$S9FCNKZRFI{ST2FZA_23](https://user-images.githubusercontent.com/11640864/58526123-900ea300-8200-11e9-986d-826e55bedbcb.png)

**Comment by Racer23** [comment]
刷新数据后 头部数据出错；item界面本没间隙的居然给隔那么开垂直间隙

**Comment by Racer23** [comment]
我让tab为0 首次加载就正常 麻烦大神看下怎么处理
![Screenshot_2019-05-29-11-07-55-084_com sevenmmobi](https://user-images.githubusercontent.com/11640864/58526652-2becde80-8202-11e9-9437-e83c03b6e6a9.png)
![54 E 0I K@HL`11J$7~EGSE](https://user-images.githubusercontent.com/11640864/58526654-314a2900-8202-11e9-9256-180563c59a7f.png)

**Comment by Racer23** [comment]
若若补充下图二情况 当前是去除缓存的 获取getgroupname为A时 却显示M
若开启缓存 刷新时清除缓存 getgroupname为A 这会会显示A

**Comment by Racer23** [comment]
异常发生在前两项 后面的正常
![Screenshot_2019-05-29-11-19-33-336_com sevenmmobi](https://user-images.githubusercontent.com/11640864/58527051-b7b33a80-8203-11e9-9c72-4392a998293e.png)
![Screenshot_2019-05-29-11-20-40-555_com sevenmmobi](https://user-images.githubusercontent.com/11640864/58527075-d3b6dc00-8203-11e9-8e21-1c8f7344663a.png)

**Comment by Gavin-ZYX** [comment]
好的，我近期处理一下。
谢谢

**Comment by Racer23** [comment]
> 好的，我近期处理一下。
> 谢谢

还有个呢就是升级support-v7到26.1.0版本时，GridLayoutManager首个子项高度会被吃掉一半

**Comment by Racer23** [comment]
> 好的，我近期处理一下。
> 谢谢

![Screenshot_2019-05-31-16-54-44-319_com sevenmmobi](https://user-images.githubusercontent.com/11640864/58694138-e298bc80-83c4-11e9-9b2b-4f77f4e8e438.png)

**Comment by Gavin-ZYX** [comment]
不好意思啊，处理得有点晚。
问题在1.5.0中已解决。

**Comment by Racer23** [comment]
> 不好意思啊，处理得有点晚。
> 问题在1.5.0中已解决。

\(^o^)/~
