### ISSUE TITLE
StickyDecoration有Header情况最后一组的名字不会绘制上去

### ISSUE THREAD

**Issue by lhj1079947827** [Gavin-ZYX/StickyDecoration#76]
StickyDecoration有header的时候如果设置setHeaderCount（1）的时候最后一组的文字不会绘制出来

**Comment by Gavin-ZYX** [comment]
你实际上有header吗？

**Comment by lhj1079947827** [comment]
有的 我使用了BaseRecyclerViewAdapterHelper来设置设置的Header

**Comment by lhj1079947827** [comment]
[
![image](https://user-images.githubusercontent.com/20966610/62598708-d711c680-b91c-11e9-8616-06166c64fe1b.png)
](url)

**Comment by Gavin-ZYX** [comment]
只是最后一组没有绘制，其他的都正常吗？

**Comment by lhj1079947827** [comment]
是的只会最后一组没有绘制名字，其他都是正常的。

**Comment by Gavin-ZYX** [comment]
最后一组有多少几条数据，我找个时间处理一下。
如果方便的话，提供一下完整的数据。

**Comment by lhj1079947827** [comment]
如图[
![image](https://user-images.githubusercontent.com/20966610/62599502-fad60c00-b91e-11e9-9ea9-0d13db4e317c.png)
](url)
我有发现了一个问题问题，如上图我只有两个数据刚好这两个数据又是分组的，就会导致顺序是错乱的应该我的上面第一个是单选题 ，第二个是简答题这样子才对

**Comment by lhj1079947827** [comment]
最后一组只有一个数据时候出现，不会绘制文字

**Comment by lhj1079947827** [comment]
再来一个bug[
![image](https://user-images.githubusercontent.com/20966610/62599758-a97a4c80-b91f-11e9-8a08-b0ee602ca850.png)
](url)
如上图如果我单选题只有一个数据时候简答题有两条数据就会出现上面的情况，分组错误

**Comment by Gavin-ZYX** [comment]
上图你有header吗？

**Comment by lhj1079947827** [comment]
都是有header的情况

**Comment by Gavin-ZYX** [comment]
感觉可能是设置header数量的问题，你要确认一下，你**真实header的数量**和你设置的数量是一致的。
这个我也找个时间去看看你用的那个Adapter的实现，里面可能有隐藏的header。把你用的那个Adapter地址发我下

**Comment by lhj1079947827** [comment]
是一致的，你看我的上面截图代码嘛 哪里我设置就是一，我也只添加了一个header

**Comment by lhj1079947827** [comment]
我用的是BaseItemDraggableAdapter因为我要实现拖拽，

**Comment by Gavin-ZYX** [comment]
这要看他是怎么实现的，你只设置一个header，不代表实际上就是一个header。
这要去看人家的源码才知道

**Comment by lhj1079947827** [comment]
他的源码我看了实现很简单啊，就是用多布局实现的header 但是这个header使用一个LinearLayout来包裹的里面可以添加多个Header就是这么简单,简单看了下源码，你的header是怎么判断法

**Comment by lhj1079947827** [comment]
[
![image](https://user-images.githubusercontent.com/20966610/62600440-71740900-b921-11e9-84fc-9c90021797ca.png)
](url)

**Comment by lhj1079947827** [comment]
[
![image](https://user-images.githubusercontent.com/20966610/62600516-ada76980-b921-11e9-82ba-b68da5f0a7a3.png)
](url)

**Comment by lhj1079947827** [comment]
不设置header的话上面bug一个都不会出现，很正常

**Comment by lhj1079947827** [comment]
我暂时用CoordinatorLayout来实现header嵌套滚动吧解决上述问题吧，谢谢你啊

**Comment by Gavin-ZYX** [comment]
这是个问题，我晚上处理一下

**Comment by lhj1079947827** [comment]
谢谢了

**Comment by Gavin-ZYX** [comment]
1.5.1 中已修复，谢谢反馈
