### ISSUE TITLE
GridLayoutManager时，每组数量较少时，会出现头部重叠的BUG

### ISSUE THREAD

**Issue by liangzhanncu** [Gavin-ZYX/StickyDecoration#77]
根据断点，是这个判断方法isLastLineInGroup(parent, position)返回了false，导致的问题，viewBottom已经显示了正确上移的位置，由于isLastLineInGroup(parent, position)返回false，所以显示重叠；
再断点下去，是nextGroupName == null导致；
实际就是Group数量小于等于spanCount的情况时会出现，没有考虑这种情况，需要校验下；
条目item的高度较高时，能把屏幕占满会出现；

**Comment by Gavin-ZYX** [comment]
感谢反馈。item数量少的情况应该已经考虑过了。你现在是item超过屏幕高度了吗？

**Comment by liangzhanncu** [comment]
代码中正常情况+1，
int findCount = 1;
GridLayoutManager布局时，如果每个分类下只有1项的情况，下面的计算方式就导致获取nextGroupName为空，实际上nextGroupName是存在的；
int findCount = spanCount - (realPosition - firstPositionInGroup) % spanCount;

**Comment by liangzhanncu** [comment]
realPosition和firstPositionInGroup相等的情况，就出现findCount == spanCount，这时获取的下一个直接加spanCount就对应不上了

**Comment by liangzhanncu** [comment]
![image](https://user-images.githubusercontent.com/24293211/63854082-dd044000-c9ce-11e9-8f0a-58d7c947653f.png)

**Comment by Gavin-ZYX** [comment]
感谢你的细心反馈，在v1.5.2中已解决。
（本身是想防止外面给我传null的时候，默认合并到上一个Group，看来不能这个干了~~）
