### ISSUE TITLE
在商米M2 android 7.1.2 显示title 会有一块黑色得

### ISSUE THREAD

**Issue by Jsondx** [Gavin-ZYX/StickyDecoration#78]
如图
![image](https://user-images.githubusercontent.com/23163675/64305929-9a8cc580-cfc3-11e9-84c1-25504295d13e.png)

**Comment by Jsondx** [comment]
代码如下 xml 布局都是   wrap_content：

        val value = object : PowerGroupListener {
            override fun getGroupName(position: Int): String {
                return topDateList[position]
            }

            override fun getGroupView(position: Int): View {
                val view = layoutInflater.inflate(R.layout.item_hos_order_suspension, null)
                val tvTitle = view.findViewById<TextView>(R.id.tv_hos_order_suspension_title)
                tvTitle.text = topDateList[position]
                return view
            }
        }
        val decoration = PowerfulStickyDecoration.Builder
                .init(value)
                .build()
        rv_hos_all_recycler.layoutManager = LinearLayoutManager(context)

**Comment by Jsondx** [comment]
如果指定得title得高度 屏幕是720  * 1080 ：title 显示得特别大。在1920*1080大小显示可以
如图
![image](https://user-images.githubusercontent.com/23163675/64306190-7382c380-cfc4-11e9-91d7-dd9a5f7be4bf.png)
![image](https://user-images.githubusercontent.com/23163675/64306192-7a113b00-cfc4-11e9-8c66-39e2da85066a.png)

**Comment by Gavin-ZYX** [comment]
建议调用下setGroupHeight设置高度，不设置高度可能会有问题

**Comment by Jsondx** [comment]
> 建议调用下setGroupHeight设置高度，不设置高度可能会有问题

好的，这边已设置 没有问题了。感谢
