### ISSUE TITLE
设置字体颜色没用

### ISSUE THREAD

**Issue by LxzBUG** [Gavin-ZYX/StickyDecoration#8]
.setGroupTextColor(Color.BLACK) 无效

**Comment by Gavin-ZYX** [comment]
请这样用：. setGroupTextColor (getResources().getColor(Color.BLACK))

**Comment by DuckDeck** [comment]
我也有这个问题，我看了源代码，是你没有设置画笔颜色

**Comment by Gavin-ZYX** [comment]
我疏忽了，已更新。谢谢
