### ISSUE TITLE
如何给悬浮的itemDecoration渐隐动画

### ISSUE THREAD

**Issue by Luopan1** [Gavin-ZYX/StickyDecoration#88]
当列表滑动时  悬浮itemDecoration显示出来  让停止滑动 需要一个渐隐的动画效果 让悬浮的view慢慢隐藏，尝试了动画  使用groupView去开启动画 动画都不执行

**Comment by Gavin-ZYX** [comment]
目前这种绘制的方式，可能不太符合你的需求，如果要有动画，得调整下绘制的代码了
