### ISSUE TITLE
PowerfulStickyDecoration  setCacheEnable 方法无效

### ISSUE THREAD

**Issue by Samdogcom** [Gavin-ZYX/StickyDecoration#94]
public void setCacheEnable(boolean b) {
        mHeadViewCache.isCacheable(b);
    }

这里没有设置mBitmapCache所以默认mBitmapCache是使用Cache的
当插入数据的时候显示就有机会错乱,因为以为把Cache关掉了,更新数据就不用调用clearCache了
导致找这个问题数小时,最后还是得每次clearCache一下

**Comment by Gavin-ZYX** [comment]
1.6.0中已修复
