### ISSUE TITLE
依赖说明应该改一下了

### ISSUE THREAD

**Issue by Samdogcom** [Gavin-ZYX/StickyDecoration#97]
implementation 'com.github.Gavin-ZYX:StickyDecoration:1.6.1'
按说明上写的添加无法找到1.6以后的版本

另外在使用PowerfulStickyDecoration的时候发现setHeaderCount好像无法适配增加了头部布局的情况
在2个回调里的position会错乱,因为时间有点久不太记得细节

**Comment by yangcheng** [comment]
应该用 
```
 'com.github.Gavin-ZYX:StickyDecoration:1.6.1'

```
还是
```
    'com.gavin.com.library:stickyDecoration:1.6.1'

```

**Comment by Gavin-ZYX** [comment]
多谢指出，已更新
